### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by ToneZe** [G-Naughty/PCLDet#2]
After carefully reading this code, the three key modules in the roihead were trained in the latest mmrotation. Although the value of the map exists, it is difficult to reduce the loss. Can the code be further optimized? I hope to mark the modified content. Nice code and paper.

**Comment by clanguagesh** [comment]
Have you encountered this error?RuntimeError: Function 'MmBackward0' returned nan values in its 0th output.
/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/models/losses/contrastive_proxy_anchor_loss.py:73: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  P_one_hot = torch.eq(labels, class_label.T).float().cuda()
/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in MmBackward0. Traceback of forward call that caused the error:
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/tools/train.py", line 203, in <module>
    main()
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/tools/train.py", line 192, in main
    train_detector(
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 149, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/models/detectors/two_stage.py", line 147, in forward_train
    roi_losses = self.roi_head.forward_train(x, img_metas, proposal_list,
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/models/roi_heads/contrastive/con_oriented_standard_roi_head.py", line 72, in forward_train
    bbox_results = self._bbox_forward_train(x, sampling_results,
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/models/roi_heads/contrastive/con_oriented_standard_roi_head.py", line 101, in _bbox_forward_train
    loss_bbox = self.bbox_head.loss(bbox_results['cls_score'],
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 236, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/models/roi_heads/bbox_heads/contrastive/contastive_convfc_rbbox_head.py", line 203, in loss
    loss_contrast= self.loss_contrast(contrast_feature, labels)  #仿ployiouloss  重新计算iou？
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/models/losses/contrastive_proxy_anchor_loss.py", line 70, in forward
    cos = F.linear(X, P)  # Calcluate cosine similarity
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.float16
torch.float16
Traceback (most recent call last):
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/tools/train.py", line 203, in <module>
    main()
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/tools/train.py", line 192, in main
    train_detector(
  File "/home/shenhui/FAIR1M/code/Large-Selective-Kernel-Network-main/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_iter')
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/mmcv/runner/hooks/optimizer.py", line 290, in after_train_iter
    self.loss_scaler.scale(runner.outputs['loss']).backward()
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/miniconda3/envs/LSKNet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'MmBackward0' returned nan values in its 0th output.
